# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 942b10c90d353e5ff0d606611c7eb96fd9eab5a56c5f2d8afd2f33b32e7d7e7764f09c84b7fb3edd7036a8d50acf6fe5751a1f37af8886e68f9189582c7de3c6

test:
  secret_key_base: ad969f582eb817914d84194478b2c5874b431557e126fc271bd823c3065ef40dfff5a9d53dc385bec4a23f1077c683cdcf0600fd2b53d5f7ef3fc31364b347cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
